
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class gfur extends javax.swing.JFrame {
    String user;
    String item;
            int t1;
    public static Connection conn=null;
    public static ResultSet rs=null;
     public static ResultSet rs1=null;
    public static Statement stmt=null;
    public static Statement stmt1=null;

    /**
     * Creates new form gfur
     */
    public gfur(String User) {
        user=User;
         try{
            Class.forName("com.mysql.jdbc.Driver");
            
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","ssd");
            
            stmt=conn.createStatement();
            stmt1=conn.createStatement();
            
            String n1="SELECT * FROM test.inventry ";
            rs=stmt.executeQuery(n1);
        //rs.next();
            
             //String sql;
            //sql = "SELECT *  FROM Admins";
             //rs = stmt.executeQuery(sql);
            //rs.next();
             
        }
         catch(Exception e)
        {
        }
        initComponents();
        s1.setVisible(false);
         st1.setVisible(false);
          d1.setVisible(false);
           w1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        sofa = new javax.swing.JRadioButton();
        sofat = new javax.swing.JRadioButton();
        dining = new javax.swing.JRadioButton();
        wardrobes = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cost = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        len = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tcost = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        st1 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        w1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        wish = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);

        sofa.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        sofa.setForeground(new java.awt.Color(51, 51, 0));
        sofa.setText("Sofa-Sets");
        sofa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sofaActionPerformed(evt);
            }
        });

        sofat.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        sofat.setForeground(new java.awt.Color(51, 51, 0));
        sofat.setText("Sofa+Teapoys");
        sofat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sofatActionPerformed(evt);
            }
        });

        dining.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        dining.setForeground(new java.awt.Color(51, 51, 0));
        dining.setText("Dining Tables");
        dining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diningActionPerformed(evt);
            }
        });

        wardrobes.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        wardrobes.setForeground(new java.awt.Color(51, 51, 0));
        wardrobes.setText("Wardrobes");
        wardrobes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wardrobesActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText("Cost Per Item");

        cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setText("No Of Items");

        len.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lenActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 51));
        jLabel9.setText("Estimated Cost");

        calculate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calculate.setForeground(new java.awt.Color(0, 51, 51));
        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("Furniture");

        s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpage/1366x768 (1).jpg"))); // NOI18N

        st1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpage/manhattan-modern-white-leather-sofa-set-black-design-co-interior-interior-design-45719.jpg"))); // NOI18N

        d1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/v-dining-table-6-chairs.jpg"))); // NOI18N

        w1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpage/walk-in-wardrobe-2-600x344.jpg"))); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 204));
        jButton2.setText("Gallery");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpage/h.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpage/re.jpg"))); // NOI18N
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        wish.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wish.setForeground(new java.awt.Color(0, 51, 51));
        wish.setText("Add to Cart");
        wish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wishActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpage/cart.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 0));
        jLabel6.setText("MY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(d1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(368, 368, 368)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sofat)
                                        .addComponent(wardrobes)
                                        .addComponent(dining))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                                    .addComponent(w1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sofa)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel7))
                                            .addGap(60, 60, 60)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(len, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tcost, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(105, 105, 105)
                                                    .addComponent(calculate)))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                        .addGap(174, 174, 174)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(st1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(wish)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))))
                                .addGap(29, 29, 29)
                                .addComponent(sofa)
                                .addGap(43, 43, 43)
                                .addComponent(sofat)
                                .addGap(45, 45, 45)
                                .addComponent(dining))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(w1)))
                        .addGap(6, 6, 6)
                        .addComponent(wardrobes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(s1)
                        .addGap(27, 27, 27)
                        .addComponent(st1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(refresh)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(d1)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(len, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculate))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wish)
                .addGap(112, 112, 112))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpage/3d_interior_design-wallpaper-1366x768.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sofaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sofaActionPerformed
        // TODO add your handling code here:
        if(sofa.isSelected())
        {
             len.setText(null);
            tcost.setText(null);
           // bre.setText(null);
            s1.setVisible(true);
             d1.setVisible(false);
              w1.setVisible(false);
             st1.setVisible(false);
            //    tractor.setSelected(false);
            ////dulux.setSelected(false);
            //apex.setSelected(false);
            sofat.setSelected(false);
            dining.setSelected(false);
            wardrobes.setSelected(false);
            //sofa.setSelected(false);
            //bathtubs.setSelected(false);
            try{
                String c1="SELECT Cost FROM test.inventry WHERE Product_Name='sofasets'";
                rs=stmt.executeQuery(c1);
                rs.next();
                String cosi_i=rs.getString("Cost");
                cost.setText(cosi_i);
            }
            catch(Exception e)
            {

            }
        }
    }//GEN-LAST:event_sofaActionPerformed

    private void sofatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sofatActionPerformed
        // TODO add your handling code here:
         if(sofat.isSelected())
        {
             len.setText(null);
            tcost.setText(null);
            //bre.setText(null);
             s1.setVisible(false);
              d1.setVisible(false);
               w1.setVisible(false);
             st1.setVisible(true);
            //    tractor.setSelected(false);
            ////dulux.setSelected(false);
            //apex.setSelected(false);
            //sofat.setSelected(false);
            dining.setSelected(false);
            wardrobes.setSelected(false);
            sofa.setSelected(false);
            //bathtubs.setSelected(false);
            try{
                String c1="SELECT Cost FROM test.inventry WHERE Product_Name='sofa+chairs'";
                rs=stmt.executeQuery(c1);
                rs.next();
                String cosi_i=rs.getString("Cost");
                cost.setText(cosi_i);
            }
            catch(Exception e)
            {

            }
        }
    }//GEN-LAST:event_sofatActionPerformed

    private void diningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diningActionPerformed
        // TODO add your handling code here:
         if(dining.isSelected())
        {
             len.setText(null);
            tcost.setText(null);
           // bre.setText(null);
            d1.setVisible(true);
             s1.setVisible(false);
              st1.setVisible(false);
               w1.setVisible(false);
            //    tractor.setSelected(false);
            ////dulux.setSelected(false);
            //apex.setSelected(false);
            sofat.setSelected(false);
            //dining.setSelected(false);
            wardrobes.setSelected(false);
            sofa.setSelected(false);
            //bathtubs.setSelected(false);
            try{
                String c1="SELECT Cost FROM test.inventry WHERE Product_Name='dinings'";
                rs=stmt.executeQuery(c1);
                rs.next();
                String cosi_i=rs.getString("Cost");
                cost.setText(cosi_i);
            }
            catch(Exception e)
            {

            }
        }
    }//GEN-LAST:event_diningActionPerformed

    private void wardrobesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wardrobesActionPerformed
        // TODO add your handling code here:
         if(wardrobes.isSelected())
        {
             len.setText(null);
            tcost.setText(null);
            //bre.setText(null);
            d1.setVisible(false);
             s1.setVisible(false);
              st1.setVisible(false);
               w1.setVisible(true);
            //    tractor.setSelected(false);
            ////dulux.setSelected(false);
            //apex.setSelected(false);
            sofat.setSelected(false);
            dining.setSelected(false);
           // wardrobes.setSelected(false);
            sofa.setSelected(false);
            //bathtubs.setSelected(false);
            try{
                String c1="SELECT Cost FROM test.inventry WHERE Product_Name='wardrobes'";
                rs=stmt.executeQuery(c1);
                rs.next();
                String cosi_i=rs.getString("Cost");
                cost.setText(cosi_i);
            }
            catch(Exception e)
            {

            }
        }
    }//GEN-LAST:event_wardrobesActionPerformed

    private void costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costActionPerformed

    private void lenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lenActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        String l1=len.getText();
        //String b1=bre.getText();
        String c1=cost.getText();
        int x1=Integer.parseInt(l1);
        //int y1=Integer.parseInt(b1);
        int z1=Integer.parseInt(c1);
        int r1=x1*z1;
        String re1=String.valueOf(r1);
        tcost.setText(re1);
    }//GEN-LAST:event_calculateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new gallery(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        new gfur(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_refreshActionPerformed

    private void wishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wishActionPerformed
        // TODO add your handling code here:
        try{
            String e1="SELECT * FROM test.guser WHERE Name='"+user+"'";
            rs=stmt1.executeQuery(e1);
            rs.next();
            String e=rs.getString("Items");
            String c=rs.getString("Total");
            int c1=Integer.parseInt(c);
            if(sofa.isSelected())
            {
                item=e+",Sofa Set";
                String a=tcost.getText();
                int a1=Integer.parseInt(a);
                t1=c1+a1;
            }
            if(sofat.isSelected())
            {
                item=e+",Sofa&Teapoy";
                String a=tcost.getText();
                int a1=Integer.parseInt(a);
                t1=c1+a1;
            }
            if(dining.isSelected())
            {
                item=e+",Dining Tables";
                String a=tcost.getText();
                int a1=Integer.parseInt(a);
                t1=c1+a1;
            }
            if(wardrobes.isSelected())
            {
                item=e+",Wardrobes";
                String a=tcost.getText();
                int a1=Integer.parseInt(a);
                t1=c1+a1;
            }
           /* if(bathtubs.isSelected())
            {
                item=e+",Bath-tub";
                String a=tcost.getText();
                int a1=Integer.parseInt(a);
                t1=c1+a1;
            }*/

            String w1="UPDATE test.guser SET Items='"+item+"',Total='"+t1+"' WHERE Name='"+user+"'";
            stmt1.executeUpdate(w1);
            JOptionPane.showMessageDialog(null, "Item added to Wishlist!");

            String f1="SELECT * FROM test.guser WHERE Name='"+user+"'";
            rs=stmt.executeQuery(f1);
            rs.next();
            String f=rs.getString("Items");
            //String c=rs.getString("Total");
            //exist.setText(f);

            ///refresh.doClick();

        }
        catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Please Regiter!");
            new guser().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_wishActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new gcart(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gfur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gfur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gfur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gfur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String user=null;
                new gfur(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JTextField cost;
    private javax.swing.JLabel d1;
    private javax.swing.JRadioButton dining;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField len;
    private javax.swing.JButton refresh;
    private javax.swing.JLabel s1;
    private javax.swing.JRadioButton sofa;
    private javax.swing.JRadioButton sofat;
    private javax.swing.JLabel st1;
    private javax.swing.JTextField tcost;
    private javax.swing.JLabel w1;
    private javax.swing.JRadioButton wardrobes;
    private javax.swing.JButton wish;
    // End of variables declaration//GEN-END:variables
}
